### ISSUE TITLE
java.io.IOException: No bkdl config bound under dl path : /streams

### ISSUE THREAD

**Issue by czhfe** [openmessaging/benchmark#254]
**Running errors when running bookkeeper performance tests**

![image](https://user-images.githubusercontent.com/19341806/160061396-286b9e4a-9c29-40ee-8a32-f9db2e204eae.png)

1920-topic-3partitions-16kb.yaml
```yaml
name: 1920 topic / 3 partition / 16Kb

topics: 1920
partitionsPerTopic: 3
keyDistributor: "NO_KEY"
messageSize: 16384
payloadFile: "payload/payload-16kb.data"
subscriptionsPerTopic: 1
consumerPerSubscription: 1
producersPerTopic: 1
producerRate: 500000
consumerBacklogSizeGB: 0
testDurationMinutes: 10
```

bookkeeper.yaml
```yaml
name: BookKeeper
driverClass: io.openmessaging.benchmark.driver.bookkeeper.DlogBenchmarkDriver

dlogUri: distributedlog://pulsar-private-zookeeper.pulsar-private.svc.cluster.local:2181/streams

# DistributedLog specific configuration
dlogConf: |
  ########################
  # ZooKeeper Client Settings
  ########################
  # zookeeper settings
  zkSessionTimeoutSeconds=30
  zkNumRetries=0
  zkRetryStartBackoffMillis=100
  zkRetryMaxBackoffMillis=200
  # bkc zookeeper settings
  bkcZKSessionTimeoutSeconds=60
  bkcZKNumRetries=20
  bkcZKRetryStartBackoffMillis=100
  bkcZKRetryMaxBackoffMillis=200
  ########################
  # BookKeeper Client Settings
  ########################
  # bookkeeper client timeouts
  bkcWriteTimeoutSeconds=10
  bkcReadTimeoutSeconds=1
  bkcNumWorkerThreads=16
  bkc.numChannelsPerBookie=1
  ########################
  # DL Settings
  ########################
  # lock timeout
  writeLockEnabled=false
  # recover log segments in background
  recoverLogSegmentsInBackground=true
  # disable allocation pool
  enableLedgerAllocatorPool=false
  ########################
  # Writer Settings
  ########################
  # ensemble size
  bkcEnsembleSize=3
  bkcWriteQuorumSize=2
  bkcAckQuorumSize=2
  bkc.ensemblePlacementPolicy=dlshade.org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy
  bkc.allowShadedLedgerManagerFactoryClass=true
  bkc.delayEnsembleChange=true
  writerOutputBufferSize=524288
  enableImmediateFlush=false
  periodicFlushFrequencyMilliSeconds=2
  logFlushTimeoutSeconds=120
  # retention policy
  logSegmentRetentionHours=48
  # rolling ledgers (disable time rolling/enable size rolling)
  logSegmentRollingMinutes=0
  maxLogSegmentBytes=2147483648
  # rolling concurrency
  logSegmentRollingConcurrency=1
  ########################
  # Reader Settings
  ########################
  enableReadAhead=true
  readAheadMaxRecords=1000000
  readAheadBatchSize=10
  readAheadWaitTime=200
```

```shell
# generated payload
< /dev/urandom tr -dc a-zA-Z0-9 | head -c 16K > payload/payload-16kb.data

# bookkeeper performance testing
bin/benchmark \
--drivers driver-bookkeeper/bookkeeper.yaml \
workloads/1920-topic-3partitions-16kb.yaml
```
